default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: <%= ENV['DB_ENV_POSTGRES_USER'] %>
  password: <%= ENV['DB_ENV_POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: slaq_development

test:
  <<: *default
  database: slaq_test

production:
  <<: *default
  database: slaq_production
